---
kind: pipeline
type: kubernetes
name: mule-test
service_account_name: drone-pipeline

metadata:
	namespace: drone
node_selector:
	kubernetes.io/os: linux
	kubernetes.io/arch: amd64
	
trigger:
	branch:
	  - devlop
	event:
	  - push
	  - pull_request
	  
services:
	- name: liquibase-validate-curr
	  environment:
		MULE_USER: raghusantosh1807
		MULE_PASSWORD: July1807-84
		  
steps:
	- name: release-dry-run
	  environment:
		LIQUIBASE_BASE_TAG: "4.4.0"
		SERVICE_BASE_TAG: "3.1-buster0slim"
		COVERAGE_THRESHOLD: "100"
		DOTNET_USE_POLLING_FILE_WATCHER: "true"
		APP_NAME: mule-test
		GH_TOKEN:
			from_secret: github-token
	  volumes:
		- name: dockersock
		  path: /var/run
		- name: liquibase-temp
		  path: /temp/liquibase
	  when:
		event:
			- pull_request
	  command:
		-	build-scripts/download-liquibase.sh $LIQUIBASE_DIR
		-	yarn install
		-	yarn commitlint
		-	yarn release-dry-run
